### ISSUE TITLE
There was an error on Ubuntu

### ISSUE THREAD

**Issue by gaizhixin** [ChesterYue/ohmyzsh-theme-passion#1]
command not found: gdate
![image](https://user-images.githubusercontent.com/8954610/80235459-53eff680-868c-11ea-8960-2281aaddc36f.png)

**Comment by ChesterYue** [comment]
> command not found: gdate
> ![image](https://user-images.githubusercontent.com/8954610/80235459-53eff680-868c-11ea-8960-2281aaddc36f.png)

this is caused by [the difference of cmd ```date``` between linux and macOS](https://apple.stackexchange.com/questions/135742/time-in-milliseconds-since-epoch-in-the-terminal)

under linux, you can just replace ```gdate``` with ```date``` in passion.zsh-theme

**Comment by gaizhixin** [comment]
Yes, I have changed it, I just hope to add some compatibility handling

**Comment by ChesterYue** [comment]
> Yes, I have changed it, I just hope to add some compatibility handling

update [a24c93e9](https://github.com/ChesterYue/ohmyzsh-theme-passion/commit/a24c93e9e0e05a422a0b9c758e0cb9ac4bf73cb5)
