### ISSUE TITLE
how to do this?

### ISSUE THREAD

**Issue by Elektroplayer** [ChesterYue/ohmyzsh-theme-passion#10]
Say please, how you do this?

![This is an image](https://media.discordapp.net/attachments/718825766179045389/960984560278044762/unknown.png?width=510&height=121)

**Comment by MaicolAntali** [comment]
> Say please, how you do this?
> 
> 
> 
> ![This is an image](https://media.discordapp.net/attachments/718825766179045389/960984560278044762/unknown.png?width=510&height=121)
> 
> 

It's a plugin. [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions)

**Comment by Elektroplayer** [comment]
Thank

**Comment by ChesterYue** [comment]
[Plugin](https://github.com/ChesterYue/ohmyzsh-theme-passion#plugin)
