### ISSUE TITLE
error：current_time_millis:7: command not found: gdate

### ISSUE THREAD

**Issue by MrBaiYinL** [ChesterYue/ohmyzsh-theme-passion#12]
This error prompt is displayed when executing the command：

current_time_millis:7: command not found: gdate
<img width="377" alt="image" src="https://user-images.githubusercontent.com/20411922/179352021-d5a5dd77-ab72-4f6f-abf4-47cac71ead98.png">

**Comment by MrBaiYinL** [comment]
@ChesterYue

**Comment by atkvishnu** [comment]
`brew install coreutils`

**Comment by ChesterYue** [comment]
> 解决了吗？

[macOS, command not found: gdate](https://github.com/ChesterYue/ohmyzsh-theme-passion#macos-command-not-found-gdate)

**Comment by steroman** [comment]
Hello, how are you doing?

Sorry to repost on a closed thread but I started to face this error too all of a sudden. I tried all the steps indicated but I'm still facing it. Is there any chances someone could help?

![Screenshot 2024-04-29 at 09 37 38](https://github.com/ChesterYue/ohmyzsh-theme-passion/assets/45558855/6c8c6b03-c86a-41f7-97bd-56f48db5cd7a)

**Comment by jerryeca** [comment]
> Hello, how are you doing?
> 
> Sorry to repost on a closed thread but I started to face this error too all of a sudden. I tried all the steps indicated but I'm still facing it. Is there any chances someone could help?
> 
> ![Screenshot 2024-04-29 at 09 37 38](https://private-user-images.githubusercontent.com/45558855/326360274-6c8c6b03-c86a-41f7-97bd-56f48db5cd7a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODAzNjMsIm5iZiI6MTcxODk4MDA2MywicGF0aCI6Ii80NTU1ODg1NS8zMjYzNjAyNzQtNmM4YzZiMDMtYzg2YS00MWY3LTk3YmQtNTZmNDhkYjVjZDdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE0Mjc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNzI1ODU4NDAxN2U1MzQ0MTk1ZWUwYmUxNzRjNGJmYzZmZmI0ZGYyZDJkMmVjYzFhNzMzZGFjNDhkYWQ3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GI0s3rWK25GOXX5ulX_u-ltCwP3PQEgZCl-Tb49CgtU)

I face the same problem

**Comment by nicolae-nn** [comment]
After installing coreutils with command:
`brew install coreutils `

The PATH variable is updated in .zshrc, however it is at the bottom of the file. Move the following line from .zshrc:
`export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";`

to a line before the
`ZSH_THEME="passion"`

That fixed it for me. Hope it helps.

**Comment by jerryeca** [comment]
> After installing coreutils with command: `brew install coreutils `
> 
> The PATH variable is updated in .zshrc, however it is at the bottom of the file. Move the following line from .zshrc: `export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";`
> 
> to a line before the `ZSH_THEME="passion"`
> 
> That fixed it for me. Hope it helps.

thanks
