### ISSUE TITLE
showing below error when ever i type command in terminal

### ISSUE THREAD

**Issue by bkash775** [ChesterYue/ohmyzsh-theme-passion#13]
error:output_command_execute_after:25: command not found: bc

**Comment by ntlyaraujo** [comment]
I also need some help on it.

**Comment by chaameliiia** [comment]
Are you using Linux? Then you need to install bc.
You can find details about installing bc here: [How to Use GNU bc (Basic Calculator) in Linux](https://www.bing.com/ck/a?!&&p=370cbc74d23d5168JmltdHM9MTY3NzgwMTYwMCZpZ3VpZD0wOTc1NzgxMi0xMjExLTZmZmUtMDZkYS02YWRhMTMzOTZlYTQmaW5zaWQ9NTQ0MA&ptn=3&hsh=3&fclid=09757812-1211-6ffe-06da-6ada13396ea4&psq=install+bc&u=a1aHR0cHM6Ly93d3cudGVjbWludC5jb20vYmMtY29tbWFuZC1leGFtcGxlcy8jOn46dGV4dD1JZiUyMHlvdSUyMGRvbiVFMiU4MCU5OXQlMjBoYXZlJTIwYmMlMjBvbiUyMHlvdXIlMjBzeXN0ZW0lMkMsY29tbWFuZCUyMHByb21wdCUyMGFuZCUyMHNpbXBseSUyMHN0YXJ0JTIwY2FsY3VsYXRpbmclMjB5b3VyJTIwZXhwcmVzc2lvbnMu&ntb=1)

**Comment by ChesterYue** [comment]
[Linux, command not found: bc](https://github.com/ChesterYue/ohmyzsh-theme-passion#linux-command-not-found-bc)

**Comment by ChesterYue** [comment]
> error:output_command_execute_after:25: command not found: bc

[Linux, command not found: bc](https://github.com/ChesterYue/ohmyzsh-theme-passion#linux-command-not-found-bc)

**Comment by ChesterYue** [comment]
> I also need some help on it.

[Linux, command not found: bc](https://github.com/ChesterYue/ohmyzsh-theme-passion#linux-command-not-found-bc)

**Comment by weiensong** [comment]
in ubuntu: sudo apt install bc
