### ISSUE TITLE
What's the meaning of this number?

### ISSUE THREAD

**Issue by xiaocaiaaaa** [ChesterYue/ohmyzsh-theme-passion#14]
<img width="709" alt="Snipaste_2022-07-21_23-11-05" src="https://user-images.githubusercontent.com/59184986/180249091-58867c7f-471d-40b2-bedf-316da99451fe.png">

**Comment by xiaocaiaaaa** [comment]
ah, got it, it's used to record the number of codes you have entered

**Comment by ChesterYue** [comment]
> <img alt="Snipaste_2022-07-21_23-11-05" width="709" src="https://user-images.githubusercontent.com/59184986/180249091-58867c7f-471d-40b2-bedf-316da99451fe.png">

this issue fixed;
see also: https://github.com/ChesterYue/ohmyzsh-theme-passion/pull/11
