### ISSUE TITLE
What's the color theme you use in your demo gif?

### ISSUE THREAD

**Issue by curryhuang** [ChesterYue/ohmyzsh-theme-passion#2]
I like it, could you please share the theme name?

**Comment by ChesterYue** [comment]
I just customized these colors myself. You can copy it from this image. Or I can share ```~/Library/Preferences/com.googlecode.iterm2.plist``` with you.

<img width="1040" alt="Screen Shot 2020-05-04 at 11 12 19" src="https://user-images.githubusercontent.com/8273263/80933900-39d6b680-8df8-11ea-877b-e038f4bb236d.png">

**Comment by curryhuang** [comment]
Thanks for sharing~

**Comment by daveyholler** [comment]
For anyone else that might come looking, I exported these colors from iTerm. You can download them here. https://www.dropbox.com/s/gbnmaxgr291qabz/Passion.itermcolors?dl=0

Thanks @ChesterYue for such a killer ZSH theme!
