### ISSUE TITLE
Minor fix: Incorrect reference to zsh dotfile in README

### ISSUE THREAD

**Issue by davidptclark** [ChesterYue/ohmyzsh-theme-passion#23]
There are several incorrect references to the zsh dotfile within the readme (at least for MacOS users):

i.e. `source ~./zshrc' should be `source ~/.zshrc'.

There are only a handful of references but fixing this should prevent needless troubleshooting for new users. Happy to perform the fix on a feature branch and create a PR, if granted permissions.

**Comment by davidptclark** [comment]
Type fixed by @ChesterYue - closing issue.

**Comment by ChesterYue** [comment]
Thx for reporting this issue.
