### ISSUE TITLE
The current git branch not showing up.

### ISSUE THREAD

**Issue by teukureynld** [ChesterYue/ohmyzsh-theme-passion#24]
![image](https://github.com/ChesterYue/ohmyzsh-theme-passion/assets/91148295/76cc297e-f527-4175-a119-2d43b2f8fdfd)

After i installed of course with the step at the marksdown... in a few minutes there is no curent git branch name, what should i do to fix this?

**Comment by RabbitKevin** [comment]
same issue.
linux: Amazon Linux 2
zsh: zsh 5.9 (x86_64-pc-linux-gnu)
oh-my-zsh: bf713e2

short solution:
I rollback oh-my-zsh to 3e05bef (the one works well in my laptop) and it's working.

**Comment by chalo2000** [comment]
[This](https://github.com/ohmyzsh/ohmyzsh/commit/04007a0e5d0a458efff23da896cf70dc40df585d) seems to be the commit that caused the issue.

**Comment by daronspence** [comment]
I'm seeing this as well. Would be cool if it was fixed in the theme directly! I assume it's a setting in the theme itself...

**Comment by daronspence** [comment]
I found some more info in https://github.com/ohmyzsh/ohmyzsh/issues/12328

You can "fix" the prompt by modifying the theme thusly:

```shell
function update_git_status() {
    # GIT_STATUS=$(git_prompt_info);
    GIT_STATUS=$(_omz_git_prompt_info);
}
```

**Comment by teukureynld** [comment]
Thanks for the help mr daron.
