### ISSUE TITLE
About the information in the bottom line on the terminal screen

### ISSUE THREAD

**Issue by SAMI3SS** [ChesterYue/ohmyzsh-theme-passion#25]
<img width="821" alt="image" src="https://github.com/ChesterYue/ohmyzsh-theme-passion/assets/64982106/03bc4eb9-3c44-4b46-a12d-823602733cbb">

Hello,
How did you add the information under the terminal here to the terminal?

Thank you from now.

**Comment by pr4zka** [comment]
me gustaria saber lo mismo

**Comment by hulleyrob** [comment]
looks like the status bar in iterm2 to me.

**Comment by ChesterYue** [comment]
iTerm config;

[Extra Preferences](https://github.com/ChesterYue/ohmyzsh-theme-passion?tab=readme-ov-file#extra-preferences) - Status Bar
