### ISSUE TITLE
shell exit in Centos 7

### ISSUE THREAD

**Issue by novNorthSea** [ChesterYue/ohmyzsh-theme-passion#4]
The shell exits a few seconds after I launch a shell.

**Comment by zsichen** [comment]
I have the same issues . Try to add code below into a comment will stop crashing problem.
`
 #TMOUT=1;
`

**Comment by waynezhangw** [comment]
I have the same issues. How can we fix it without losing the real-time prefix display?

**Comment by Alwaysproblem** [comment]
same issue
