### ISSUE TITLE
how to install step by step

### ISSUE THREAD

**Issue by kd-s-t** [ChesterYue/ohmyzsh-theme-passion#9]

**Comment by entergame1994** [comment]
1. Go to $ZSH_CUSTOM/themes and touch passion.zsh-theme.
2. Edit it, e.g. with vi and copy [https://github.com/ChesterYue/ohmyzsh-theme-passion/blob/master/passion.zsh-theme].
3. Go to ~/.zshrc and edit it by changing $ZSH_THEME to passion
4. Type exit and open the terminal once again.

Obiously, you need to have ohmyzsh installed.

**Comment by renegadec** [comment]
got it after a few troubles getting it, thanks

**Comment by zoonim116** [comment]
1) `git clone git@github.com:ChesterYue/ohmyzsh-theme-passion.git ${ZSH_CUSTOM}/themes/Passion`
2) `nano ~/.zshrc`
3) Change ZSH_THEME to `ZSH_THEME="Passion/passion"`
4) Profit

P.S also you need to add `git-prompt` to a list of plugins

**Comment by JoeriTheGreat** [comment]
If you get an error:
```
Cloning into '/Users/username/.oh-my-zsh/custom/themes/Passion'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Use following command to clone it
git clone https://github.com/ChesterYue/ohmyzsh-theme-passion ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/Passion

**Comment by ChesterYue** [comment]
follow [Usage](https://github.com/ChesterYue/ohmyzsh-theme-passion#usage)
